// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StringReverseService.DBContext;

namespace StringReverseService.Migrations
{
    [DbContext(typeof(InputStringContext))]
    partial class InputStringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StringReverseService.Models.InputString", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("InputValue")
                        .IsRequired();

                    b.Property<DateTime>("RequestedOn");

                    b.HasKey("Id");

                    b.ToTable("InputStrings");

                    b.HasData(
                        new { Id = new Guid("cfe5626b-d99d-4577-91a6-4171c0145035"), InputValue = "TestValue", RequestedOn = new DateTime(2021, 7, 1, 0, 32, 41, 437, DateTimeKind.Utc) }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
